services:
  # PostgreSQL Database Service
  db:
    image: postgres:17
    container_name: django_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  
  # Redis
  redis:
    image: redis:8.0-alpine
    container_name: django_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: always

  # Django Web Application Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        APP_PORT: ${APP_PORT:-8000}
    container_name: django_web
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      APP_PORT: ${APP_PORT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./sent_emails:/app/sent_emails
      - ./media:/app/media
      - ./logs:/app/logs
    restart: always

  # Celery Worker Service
  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        APP_PORT: ${APP_PORT:-8000}
    container_name: django_celery
    command: celery -A config worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: always

  # Celery Beat Service
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        APP_PORT: ${APP_PORT:-8000}
    container_name: django_celery_beat
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: always

volumes:
  db_data:
  redis_data:

