# Generated by Django 5.2.7 on 2025-11-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
