# Generated by Django 5.2.7 on 2025-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextiq', '0002_alter_document_parse_content_status_querylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
